# Lab Assignment 5: Lists, Stacks, Queues, and Arrays

In [7]:
import numpy as np

## Problem 1: Cleaning fish tanks

Read "Swimmy Friends Pet Store" (pp. 51-54) in *Computational Fairy Tales*.

"fish_tanks" is a list representing the fish tanks in the store.

In [2]:
fish_tanks = ['Neon Tetras','Guppies','Sword Tails','Piranha','Goldfish','Tiger Barbs']
fish_tanks

['Neon Tetras', 'Guppies', 'Sword Tails', 'Piranha', 'Goldfish', 'Tiger Barbs']

We also have an empty fish tank.

In [3]:
empty_tank = [None]
empty_tank

[None]

Swap the Neon Tetras and Tiger Barbs using the empty tank, making sure that the length of the fish_tanks list doesn't change and you're not replicating fish.

First, put the tetras in the empty tank.

In [ ]:
# Put the neon tetras into the empty tank


# Remove the neon tetras, leaving an empty tank behind


# Check the status of everybody
print(fish_tanks)
print(empty_tank)

Second, move the tiger barbs to the old tetra tank.

In [ ]:
# Put the tiger barbs in the old tetra tank

# Remove the tiger barbs, leaving an empty tank behind


# Check the status of everybody
print(fish_tanks)
print(empty_tank)

Third, move the tetras to the old tiger barb tank.

In [ ]:
# Put the tetras in the old tiger barb tank

# Remove the tetras from the empty tank

# Check the status of everybody
print(fish_tanks)
print(empty_tank)

Instead of doing a single swap, let's rotate all the fish in the tanks. Write a function to move each set of fish two tanks to the right, printing out the status along the way.

Before we do that, let's look at a helpful Python function called [`enumerate`](https://docs.python.org/3.5/library/functions.html#enumerate). It gives us an integer corresponding to our position in the iterable (a list in this case) as well the element itself. We can catch both the position integer and the iterable element by declaring two temporary variables "pos" and "tank" for use within the loop.

In [4]:
for pos,tank in enumerate(fish_tanks):
    print(pos,tank)

0 Neon Tetras
1 Guppies
2 Sword Tails
3 Piranha
4 Goldfish
5 Tiger Barbs


Now define a `move_fish` function that takes three arguments:

* **fish_tanks** is a list of fish in their tanks
* **empty_tank** is a list where we can put a fish
* **steps** is how many tanks down the fish should be moved

In [ ]:
def move_fish(fish_tanks,empty_tank,steps):
    
    # Your code here
            
    return fish_tanks,empty_tank

Test the output.

In [ ]:
fish_tanks = ['Neon Tetras','Guppies','Sword Tails','Piranha','Goldfish','Tiger Barbs']
empty_tank = [None]

print(move_fish(fish_tanks,empty_tank,2)[0] == ['Goldfish', 'Tiger Barbs', 'Neon Tetras', 'Guppies', 'Sword Tails', 'Piranha'])
print(move_fish(fish_tanks,empty_tank,2)[1] == [None])

## Problem 2: Implement a karaoke machine 

Implement a `Karaoke` class emulating either the `Stack` or `Queue` definitions from class code. Load your chosen data structure with lyrics from a song, then play the song.

In [ ]:
class Karaoke(object):
    

Why did you choose to implement it as a stack or a queue?

Load lyrics into the Karaoke machine.

Play your Karaoke machine!

## Problem 3: Working in a cafeteria

Read "Cafeteria Stacks and Queues" (pp. 93-101) in *The CS Detective*.

In [5]:
class Plate(object):
    def __init__(self,plate_id):
        self.plate_id = plate_id
        self.age = 0
        
    def add_time(self):
        # Implement an add_time mutator method that increments the age attribute up by one
        
    def get_age(self):
        # Implement a get_age accessor method that returns the age of a Plate
    
    def __str__(self):
        return str(self.plate_id)
    
    def __repr__(self):
        return 'Plate {0:02d}'.format(self.plate_id)

IndentationError: expected an indented block (<ipython-input-5-fb6c70ddcb33>, line 9)

Check to make sure these all work.

In [ ]:
p = Plate(1)
p.add_time()
p

Create a `PlateStack` object that lets you put plates into it.

In [ ]:
class PlateStack(object):
    def __init__(self):
        self.plates = []
        
    def unload(self):
        if self.is_empty():
            raise RuntimeError('Cannot unload an empty stack of plates')
            
        # Include a subroutine that increments each plate's age in the stackusing the add_time method
        
        top_idx = len(self.plates) - 1
        plate = self.plates[top_idx]
        del self.plates[top_idx]
        return plate
    
    def load(self,plate):
        # Include a subroutine that increments each plate's age in the stack using the add_time method
        
        self.plates.append(plate)
        
    def top(self):
        if self.is_empty():
            raise RuntimeError('Empty stack has no top')
            
        top_idx = len(self.plates) - 1
        return self.plates[top_idx]
    
    def ages(self):
        return [{'Plate {0:02d}'.format(p.plate_id):'{0} min'.format(p.get_age())} for p in self.plates]
    
    def is_empty(self):
        return len(self.plates) == 0
    
    def __len__(self):
        return len(self.plates)
    
    def __repr__(self):
        return 'PlateStack('+str(self.plates)+')'

Test out the class with a basic example.

In [ ]:
plate_stack = PlateStack()
plate_stack.load(Plate(0))
plate_stack

Put a bunch of plates on.

In [ ]:
t = 1

while t < 10:
    plate_stack.load(Plate(t))
    t += 1
    
plate_stack

Get their ages and current order.

In [ ]:
plate_stack.ages()

For 6 minutes, take a plate off and put it back on.

In [ ]:
for i in range(6):
    print("Taking Plate {0:02d} off!".format(plate_stack.top().plate_id))
    old_plate = plate_stack.unload()
    
    #new_plate_id = len(plate_stack)
    print("Loading Plate {0:02d} on!".format(old_plate.plate_id))
    plate_stack.load(Plate(old_plate.plate_id))

Check the ages and order of the PlateStack after the 6 minutes of furious plate stacking action.

In [ ]:
plate_stack.ages()

Compare a PlateStack approach to a PlateQueue approach.

In [ ]:
class PlateQueue(object):
    
    def __init__(self):
        self.plates = []
    
    def load(self,plate):
        # Include a subroutine that increments each plate's age in the stack using the add_time method
        
        self.plates.append(plate)
        
    def unload(self):
        if self.is_empty():
            raise RuntimeError('Cannot pop an empty stack')
        
        # Include a subroutine that increments each plate's age in the stack using the add_time method
        
        plate = self.plates[0]
        del self.plates[0]
        return plate
    
    def ages(self):
        return [{'Plate {0:02d}'.format(p.plate_id):'{0} min'.format(p.get_age())} for p in self.plates]
        
    def front(self):
        if self.is_empty():
            raise RuntimeError('Cannot access front of empty queue')
        else:
            return self.plates[0]
        
    def is_empty(self):
        return len(self.plates) == 0
    
    def __len__(self):
        return len(self.plates)
    
    def __repr__(self):
        return 'PlateQueue('+str(self.plates)+')'

Test out the PlateQueue.

In [ ]:
plate_queue = PlateQueue()
plate_queue.load(Plate(0))
plate_queue

Load up the PlateQueue with a few different plates.

In [ ]:
t = 1

while t < 10:
    plate_queue.load(Plate(t))
    t += 1
    
plate_queue

Check all their ages.

In [ ]:
plate_queue.ages()

Now take plates off the queue and put them back on.

In [ ]:
for i in range(6):
    print("Taking Plate {0:02d} off!".format(plate_queue.front().plate_id))
    old_plate = plate_queue.unload()
    
    #new_plate_id = len(plate_queue)
    print("Loading Plate {0:02d} on!".format(old_plate.plate_id))
    plate_queue.load(Plate(old_plate.plate_id))

Check the ages and order of the PlateQueue after the 6 minutes of furious plate stacking action.

In [ ]:
plate_queue.ages()

Is the PlateQueue or PlateStack doing a better job at keeping the plates fresh?

## Problem 4: Making an (incorrect) Sudoku board

Let's stretch our legs with numpy. Use a combination of [`np.arange`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) and [`np.repeat`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) to generate all the values we'll need for a complete [Sudoku board](https://en.wikipedia.org/wiki/Sudoku).

In [ ]:
sudoku_numbers = np.repeat(np.arange(),)

Use [`np.shuffle`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.shuffle.html) to shuffle the values of these number randomly. 

Why do we not assign the output of this function to a new variable like "shuffled_numbers"? What in the documentation about this function is the clue about how to use this function?

In [ ]:
np.random.shuffle(sudoku_numbers)
sudoku_numbers

Use the [`np.reshape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) function on your shuffled sudoku numbers to generate a "sudoku_board" containing 3x3 of 3x3 cells.

In [ ]:
sudoku_board = sudoku_numbers.reshape()
sudoku_board

How do you access the most upper-left number in the entire game board?

How do you access the most upper-right number in the entire game board?

How do you access the most lower-left number in the entire game board?

How do you access the most lower-right number in the entire game board?

How do you access the number at the center of the game board?

All three tests must pass as `True`.

In [ ]:
_shape = tuple(np.random.choice(np.arange(3,4),4))
sudoku_board.size == 81, sudoku_board.ndim == 4, sudoku_board.shape == _shape

## Extra Credit

I'm going to give you a "solved_board" as a test case to use here on out. You can visualize it from the [Wikipedia article](https://en.wikipedia.org/wiki/Sudoku):

![Solved sudoku](http://i.imgur.com/etZoZkw.png)

In [8]:
solved_board = np.array([[[[5, 3, 4],[6, 7, 2],[1, 9, 8]],[[6, 7, 8],[1, 9, 5],[3, 4, 2]],[[9, 1, 2],[3, 4, 8],[5, 6, 7]]],[[[8, 5, 9],[4, 2, 6],[7, 1, 3]],[[7, 6, 1],[8, 5, 3],[9, 2, 4]],[[4, 2, 3],[7, 9, 1],[8, 5, 6]]],[[[9, 6, 1],[2, 8, 7],[3, 4, 5]],[[5, 3, 7],[4, 1, 9],[2, 8, 6]],[[2, 8, 4],[6, 3, 5],[1, 7, 9]]]])
solved_board

array([[[[5, 3, 4],
         [6, 7, 2],
         [1, 9, 8]],

        [[6, 7, 8],
         [1, 9, 5],
         [3, 4, 2]],

        [[9, 1, 2],
         [3, 4, 8],
         [5, 6, 7]]],


       [[[8, 5, 9],
         [4, 2, 6],
         [7, 1, 3]],

        [[7, 6, 1],
         [8, 5, 3],
         [9, 2, 4]],

        [[4, 2, 3],
         [7, 9, 1],
         [8, 5, 6]]],


       [[[9, 6, 1],
         [2, 8, 7],
         [3, 4, 5]],

        [[5, 3, 7],
         [4, 1, 9],
         [2, 8, 6]],

        [[2, 8, 4],
         [6, 3, 5],
         [1, 7, 9]]]])

We can use reshape to change our 4-dimensional shape back to a 3-dimensional shape, which *might* just be helpful if we want to loop through each sub-grid more efficiently. Rather than there being a 3x3 grid of 3x3 grids, this reshape says there are 9 3x3 grids.

In [ ]:
solved_board.reshape(9,3,3)

A Sudoku game is only solved if each column, each row, and each of the 3x3 subgrids contains the digits 1 to 9. Write three functions to check if the "sudoku_board" you generated above fulfills each of these criteria. 

The [`np.unique`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html) function may be helpful for checking if there are 9 unique elements in a subgrid, row, or column.

In [9]:
example = np.array([[5, 3, 4],[6, 7, 2],[1, 9, 8]])
np.unique(example)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

You can slice this 4D array to get all the rows out in the first subgrid row:

In [10]:
solved_board[:,:,0]

array([[[5, 3, 4],
        [6, 7, 8],
        [9, 1, 2]],

       [[8, 5, 9],
        [7, 6, 1],
        [4, 2, 3]],

       [[9, 6, 1],
        [5, 3, 7],
        [2, 8, 4]]])

We can extend this even more. This [`np.transpose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html#numpy.rollaxis) does something interesting and returns each row across subgrids as its own subgrid.

In [ ]:
np.transpose(solved_board,(2,0,1,3))

This transpose returns each column as its own subgrid. You're welcome.

In [ ]:
np.transpose(solved_board,(1,3,0,2))

If you're wondering why transpose works the way it does, it lets you swap different dimensions around. Try comparing `np.transpose(solved_board,(0,1,2,3))` with `np.transpose(solved_board,(3,2,1,0))`. 

If you're like me, transposing 4-dimension arrays melts my brain, so let's just brute force discover what are the right parameters to pass to transpose to generate the subgrid outputs we want. It turns out there's two ways to do each.

In [ ]:
from itertools import permutations

# Brute force discover the permutation parameters to generate the desired rows-to-subgrids output
for vals in list(permutations(range(4),4)):
    swapped = np.transpose(solved_board,vals)
    # An example of what I want as an output
    desired = np.array([[5,3,4],[6,7,8],[9,1,2]])
    if np.all(swapped[0,0] == desired):
        print('ROWS:',vals)

# Brute force discover the permutation parameters to generate the desired columns-to-subgrids output
for vals in list(permutations(range(4),4)):
    swapped = np.transpose(solved_board,vals)
    # An example of what I want as an output
    desired = np.array([[5,6,1],[8,4,7],[9,2,3]])
    if np.all(swapped[0,0] == desired):
        print('COLUMNS:',vals)

Now use these transpose methods in the `check_rows` and `check_columns` functions respectively. Remember, you can use the `ndarray.reshape(9,3,3)` method to save you a step in looping through rows of subgrids.

In [ ]:
def check_subgrids(sudoku_board):
    

check_subgrids(solved_board)

In [ ]:
def check_rows(sudoku_board):
    

check_rows(solved_board)

In [ ]:
def check_columns(sudoku_board):
    

check_columns(solved_board)